### ISSUE TITLE
Only use state.width in UI

### ISSUE THREAD

**Issue by frostburn** [frostburn/panel-league#14]
Remove dimension properties from `GameEngine` instances and always get them from the state.
Keyboard input is affected the most as state is not directly available there.

**Comment by RauliL** [comment]
This could be easily implemented if first state of the game would be available *before* user interface is being initialized.

**Comment by frostburn** [comment]
The engine is supposed to be stateless in the sense that you can freely access any instant of time including the initial state. Issue https://github.com/frostburn/panel-league/issues/37 should help.

I think that just making the engine dimensions immutable should be enough however. Digging up and parsing the state is probably not an efficient approach.

**Comment by frostburn** [comment]
Just making it impossible to set the engine dimension should be enough: https://github.com/frostburn/panel-league/issues/38
